language: scala
scala:
   - 2.11.8
   - 2.12.0-M4

jdk:
  - oraclejdk8

matrix:
  allow_failures:
    - scala: 2.12.0-M4

sudo: false

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - ui/node_modules

script:
   - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test
